### PR TITLE
Remove Unused Usings

### PR DESCRIPTION
**Pull request by Coop56**
This PR just removes any usings / imports that weren't being used and could be safely removed.

### CODE REVIEW

**Comment by Coop56** [comment]
Converted to Draft just so it doesn't get merged until we're ready.

**Comment by sadukie** [comment]
Looking at this versus #1169 - the merge conflicts aren't as horrible as we think.

Tagging in @ShadyNagy on this

In the unmerged paths:

- The deleted files are getting refactored over to NimblePros.Vimeo. So we can accept the changes as deleted files.
- The modified files in the unmerged paths should be manageable conflicts. I can help work through those.

-----
Changes to be committed:
        new file:   CODE_OF_CONDUCT.md
        new file:   CONTRIBUTING.md
        modified:   src/DevBetterWeb.Core/Specs/BillingActivitiesByDateTimeRangeAndCancelledVerbSpec.cs
        modified:   src/DevBetterWeb.Core/Specs/BillingActivitiesByDateTimeRangeAndSubscribedVerbSpec.cs
        modified:   src/DevBetterWeb.Core/Specs/MemberByUserIdWithFavoriteArchiveVideosSpec.cs
        modified:   src/DevBetterWeb.Web/Program.cs

Unmerged paths:
  (use "git add/rm <file>..." as appropriate to mark resolution)
        deleted by us:   src/DevBetterWeb.Vimeo/Models/Categories.cs
        deleted by us:   src/DevBetterWeb.Vimeo/Models/DataPaged.cs
        deleted by us:   src/DevBetterWeb.Vimeo/Models/Paging.cs
        deleted by us:   src/DevBetterWeb.Vimeo/Models/Thumbnail.cs
        deleted by us:   src/DevBetterWeb.Vimeo/Models/UploadTicket.cs
        deleted by us:   src/DevBetterWeb.Vimeo/Models/Uploader.cs
        deleted by us:   src/DevBetterWeb.Vimeo/Services/VideoServices/DeleteVideoService.cs
        deleted by us:   src/DevBetterWeb.Vimeo/Services/VideoServices/GetAllAnimatedThumbnailService.GetAllAnimatedThumbnailResponse.cs
        deleted by us:   src/DevBetterWeb.Vimeo/Services/VideoServices/GetAllAnimatedThumbnailService.cs
        deleted by us:   src/DevBetterWeb.Vimeo/Services/VideoServices/GetAnimatedThumbnailService.GetAnimatedThumbnailRequest.cs
        deleted by us:   src/DevBetterWeb.Vimeo/Services/VideoServices/GetPagedVideosService.cs
        deleted by us:   src/DevBetterWeb.Vimeo/Services/VideoServices/GetStreamingTicketService.cs
        deleted by us:   src/DevBetterWeb.Vimeo/Services/VideoServices/UpdateVideoDetailsService.cs
        deleted by us:   src/DevBetterWeb.Vimeo/Services/VideoServices/UploadResumableCreateVideoLinkService.cs
        deleted by us:   src/DevBetterWeb.Vimeo/Services/VideoServices/UploadResumableVideoService.cs
        deleted by us:   src/DevBetterWeb.Web/Endpoints/VideoEndpoints/UploadVideoCreateVimeoLink.cs

        both modified:   src/DevBetterWeb.Infrastructure/DefaultInfrastructureModule.cs
        both modified:   src/DevBetterWeb.Web/Interfaces/IVideoDetailsService.cs
        both modified:   src/DevBetterWeb.Web/Pages/Admin/Videos/DeleteAll.cshtml.cs
-----

**Comment by Coop56** [comment]
I'm happy to help work through any merge conflicts as well, just let me know!

**Comment by ardalis** [comment]
Let's merge this one since it's pretty easy and then we can work on the other PRs

**Pull request merged**
