### PR TITLE
stripe refactor

### LINKED ISSUE #934: Stripe WebHooks EndPoints
We need to split the Stripe WebHooks `StripeWebhookHandler` into Endpoints for every category as we did on this `PaymentIntentWebHook`.

https://stripe.com/docs/billing/subscriptions/overview#subscription-lifecycle
https://stripe.com/docs/billing/subscriptions/webhooks

image

### PR DESCRIPTION
**Pull request by ShadyNagy**
Closes #934 
This PR is for Stripe WebHooks Endpoints.
- Names of the AppSettings changed (Stripe properties become Pascal), so we need to change it on Azure. (StripePublishableKey, StripeSecretKey, YearlyPlanId, MonthlyPlanId)

| Endpoint                           | Route                                         | AppSettings (StripeOptions)                       |
|------------------------------------|-----------------------------------------------|---------------------------------------------------|
| CustomerSubscriptionDeletedWebHook | stripe-customer-subscription-deleted-web-hook | StripeCustomerSubscriptionDeletedWebHookSecretKey |
| CustomerSubscriptionUpdatedWebHook | stripe-customer-subscription-updated-web-hook | StripeCustomerSubscriptionUpdatedWebHookSecretKey |
| InvoicePaidWebHook                 | stripe-invoice-paid-web-hook                  | StripeInvoicePaidWebHookSecretKey                 |

### CODE REVIEW

**Comment by ardalis** [comment]
No database changes, just Azure config changes, right?

**Comment by ShadyNagy** [comment]
Yes 
> No database changes, just Azure config changes, right?

**Comment by ardalis** [comment]
I was going to just add duplicate options with the pascal cased names but I got this:
image

So I guess I need to just rename them after merging this.

**Comment by ShadyNagy** [comment]
Yes, if it already exists, then we need to rename it only.

> I was going to just add duplicate options with the pascal cased names but I got this: image
> 
> So I guess I need to just rename them after merging this.

**Comment by ardalis** [comment]
What am I supposed to put in settings?
image

Key: StripeOptions:StripeCustomerSubscriptionDeletedWebHookSecretKey
Value: stripe-customer-subscription-deleted-web-hook

?

Are the routes what goes with these keys or what?

**Pull request merged**
