### PR TITLE
Pvaillancourt/910 member birthday visibility

### LINKED ISSUE #910: Member Birthday Visibility
- Make Member birthday, if set, appear on their profile
- Add more info on the edit profile page that indicates that, if set, birthday will be visible to other devBetter members and may be used to celebrate their day via Discord, coaching sessions, etc.
- Ensure the edit profile page includes a means by which to remove one's birthday

### PR DESCRIPTION
**Pull request by snowfrogdev**
- Display birthday in member's public profile
- Add a mention to the effect that the birthday will be visible to other members
- Removed numeric arrows/spinner from day and month input fields
- Added individual Day and Month labels to corresponding input fields
- Added a trash can button to easily clear both birthday fields
Closes #910 
Birthday

### CODE REVIEW

**Comment by ardalis** [comment]
Love the image demo, thanks!

**Review by ardalis — APPROVED** [review]

**Comment by Rostech** [comment]
Hey @snowfrogdev, very nice image demo indeed. Can you please share what tool did you use to do it?

**Comment by snowfrogdev** [comment]
> Hey @snowfrogdev, very nice image demo indeed. Can you please share what tool did you use to do it? 

A free tool called "Screen to Gif", available for download.

**Comment by Rostech** [comment]
Thanks, @snowfrogdev!

**Pull request merged**
